# Configuration

# -------- Location --------
# Location in latitude and longitude coordinates
lat: 53.524960
lon: -1.627447

# Format: YYYYMMDDHH
start_time: 2000010100

# Format: YYYYMMDDHH
end_time: 2000010123

# Output directory for weather records
output_dir: ./data
